Draft: Merge seperate animation files via vite plugin
MrVauxs/pf2e-graphics pull request #1
Opened 2024-07-14 20:19 UTC by oWave

- During build: Bundles all json files in the `animations` folder into one `animations.json`
- During serve (dev): Intercepts requests to `dist/animations.json` and responds with a generated bundle.
  - `handleHotUpdate` still works. Any changes to a json file in `animations` refreshes the entire bundle

TODOs (maybe)
- Conflict detection if two files have the same keys?

2024-07-14 20:30 UTC, MrVauxs commented
> TODOs (maybe)
> 
> * Conflict detection if two files have the same keys?

My idea is to create an index of duplicate keys during merging (just let JS resolve it by itself) and send it to the client to be shown through a `ui.notifications.warn`

2024-07-15 20:22 UTC, oWave commented
Alright, done. Also snuck some lines in there that create empty `dist/pf2e-graphics.{js,css}` files during dev if they don't exist yet, so foundry stops complaining

2024-07-15 20:42 UTC, MrVauxs requested changes

2024-07-15 20:42 UTC, MrVauxs commented on vite.config.ts
> +				const files = [...moduleJSON.esmodules, moduleJSON.styles].flat()
Can we be consistent here, use `...` on both or remove the spreader and just use `flat`

2024-07-15 20:42 UTC, MrVauxs commented on vite.config.ts
> +		const keys = new Set<string>()
Is this necessary? Why not compare the newly added keys directly to those inside the `animations` object?

2024-07-16 17:03 UTC, oWave commented
I forgot the in operator exists.
Side note: Setting `lib` in `tsconfig` might be nice so a few newer JS features are available (`Object.hasOwn`, `cause` for Errors)

2024-07-16 18:54 UTC, merged